name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - name: Build docker image
        run: docker build -t hmackowski/mobuli-backend-0.0.1-snapshot .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check Docker version
        run: docker --version
      - name: Pull Image from Docker Hub
        run: docker pull hmackowski/mobuli-backend-0.0.1-snapshot:latest
      - name: Delete old container
        run: docker rm -f mobuli-container || true
      - name: Run Docker container
        run: docker run -d -p 8080:8080 --name mobuli-container hmackowski/mobuli-backend-0.0.1-snapshot:latest
