name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install docker.io -y
          sudo systemctl start docker
      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - name: Build docker image
        run: docker build -t hmackowski/mobuli-backend-0.0.1-snapshot .
      - name: Publish image to docker hub
        run: docker push hmackowski/mobuli-backend-0.0.1-snapshot:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install docker.io -y
          sudo systemctl start docker
      - name: Pull image from Docker hub
        run: docker pull hmackowski/mobuli-backend-0.0.1-snapshot
      - name: Delete old container
        run: docker rm -f mobuli-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name mobuli-container hmackowski/mobuli-backend-0.0.1-snapshot:latest
